# ---- BREW
update
upgrade
cleanup

install android-platform-tools
install ffmpeg --with-x265 --with-freetype                                 
install htop-osx
install rsync
install vim --with-ruby --with-python --override-system-vi
install webp
install wget --enable-iri
install youtube-dl
install zsh --disable-etcdir

# !! NOTE !!
# required to enable all features of htop
# sudo chown root:wheel /usr/local/Cellar/htop-osx/0.8.2/bin/htop
# sudo chmod u+s /usr/local/Cellar/htop-osx/0.8.2/bin/htop
#
# !! Ack !!
# TODO: the latest version of ack conflicts with rbenv and pyenv ...
# install ack
# TODO: ensure zsh loads this
# /usr/local/share/zsh/site-functions/_ack

# ---- BREW CASK
install brew-cask
cask cleanup


cask install dropbox
cask install java
cask install jumpcut
cask install mpv
cask install spotify
cask install vlc


