#!/usr/bin/env bash

#
# Update git submodules
#
echo ">> Updating all git submodules"
git submodule update --init --recursive

#
# Link all dotfiles from the current directory
#
echo ">> Creating all symlinks"

toDir=$(pwd)
fromDir=$HOME

for dir in $(ls -a1); do
    # Skip "." and ".."
    if [ "${dir}" == "." ] || [ "${dir}" == ".." ]; then
        continue
    fi

    # Skip some git files that are specific to this repository
    if [ "${dir}" == ".git" ] \
    || [ "${dir}" == ".gitmodules" ] \
    || [ "${dir}" == ".gitignore" ] \
    || [ "${dir}" == ".gitattributes" ]; then
        continue
    fi

    # Skip all "normal" (non hidden) files
    if [ "${dir:0:1}" != "." ]; then
        continue
    fi

    linkFrom="${fromDir}/${dir}"
    linkTo="${toDir}/${dir}"

    rm -rf "${linkFrom}"
    ln -s "${linkTo}" "${linkFrom}"
done

#
# Link the keyboard layout under OSX
#
fromDir=~/Library/Keyboard\ Layouts/
layoutFile=$(ls -1 *.keylayout)

if [ -e "${fromDir}" ]; then
    echo ">> Installing new OSX keyboard layout"

    rm -rf "${fromDir}/${layoutFile}"
    ln -s "${toDir}/${layoutFile}" "${fromDir}/${layoutFile}"
fi

#
# Install vim plugins
#
echo ">> Installing all vim plugins"
vim -e -c BundleInstall -c quitall > /dev/null

#
# ZSH
#
chsh -s /bin/zsh

#
# Ruby
#
rbenv install 1.9.3-p327
rbenv global 1.9.3-p327
rbenv shell 1.9.3-p327
gem install bundler
rbenv rehash
bundle

#
# Python
#
curl -kL http://xrl.us/pythonbrewinstall | bash
pythonbrew install --no-test 2.7.3
pythonbrew switch 2.7.3
pip install virtualenv
pip install virtualenvwrapper

#
# NodeJS
#
git clone git://github.com/creationix/nvm.git ~/.nvm
nvm install v0.8.16
nvm alias default v0.8.16

#
# OSX tools / settings
#
./.osx

command -v foo >/dev/null 2>&1 \
    || ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
./brew

#
# Done! :D
#
echo ">> Done"
